version: '3.7'

services:
  app:
    image: github.com/kubakin/tk-back-ddd-cqrs.git:docker
    container_name: tk-back
    restart: always
    build:
      context: .
    env_file:
      - .env
  db:
    container_name: db
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - /var/lib/tk/postgresql:/var/lib/postgresql/data
    ports:
      - '65432:5432'

