version: '3.7'

services:
  app:
    image: github.com/kubakin/tk-back-ddd-cqrs.git
    container_name: tk-back
    restart: always
    build:
      dockerfile: Dockerfile
      context: github.com/kubakin/tk-back-ddd-cqrs.git
    env_file:
      - .env
    ports:
      - '0.0.0.0:3003:3003'
  front:
    image: github.com/kubakin/tk-game.git
    container_name: tk-front
    restart: always
    environment:
      - TEST_D=val
    build:
      dockerfile: Dockerfile
      context: github.com/kubakin/tk-game.git
    env_file:
      - .env.front
    ports:
      - '0.0.0.0:3000:3000'
    command: npm run prod
  db:
    container_name: db
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - /var/lib/tk/postgresql:/var/lib/postgresql/data
    ports:
      - '65432:5432'
